# Generated by Django 4.2.7 on 2024-01-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('birthDate', models.DateField()),
                ('Age', models.IntegerField(null=0)),
                ('gender', models.CharField(max_length=250)),
                ('phoneNumber', models.IntegerField()),
                ('Email', models.EmailField(max_length=250, primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=250)),
                ('department', models.CharField(choices=[], max_length=250)),
                ('courses', models.CharField(choices=[], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, null=True)),
                ('password', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
